spring:
  application:
    name: store-product

  datasource:
    url: jdbc:mysql://localhost:3306/shop-product?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8079/eureka

server:
  port: 8090